version: '3.11'

services:
  app_api:

    build:
      context: .

    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    tty: false

    volumes:
      - .:/app

    restart: on-failure

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on: [database, redis, celery, beat]

  database:
    image: postgres:15.3-alpine

    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_HOST: ${db_host}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data_safe_secret:/var/lib/postgresql/data

  celery:
    build:
      context: .
    restart: on-failure
    command: sh -c "celery -A config worker -l info -S django"

  beat:
    build:
      context: .
    restart: on-failure
    command: sh -c "celery -A config beat -l info -S django"

  redis:
    image: redis:6.0.16-alpine
    hostname: redis

volumes:
  postgres_data_safe_secret:
  lms_api:
  database:
    driver: local